### ISSUE TITLE
User can create a workout log

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a workout log

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can create a workout log which will contain multiple exercises.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 1 (1)](https://user-images.githubusercontent.com/68994507/181347565-2ad28265-00f7-4cd0-8c6c-f2ebaf529779.png)

Desktop
![Create workout log (desktop) #1](https://user-images.githubusercontent.com/68994507/181346534-a2b9cebc-23f8-4309-9e80-4ce68511f805.png)

## ✅ Task Lists
> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to hold users information for a workout (workoutId, userId, exercises, templateName)
- [x] Update `data.sql` to include an admin account 

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive post requests creating a new workout
- [x] Server creates a sql query to add the information to the workout table including the userId, and placeholder name with a auto-generated workoutId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
