### ISSUE TITLE
User can view exercise list

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can view a list of exercises of various body parts

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![View Exercise List (mobile) #1](https://user-images.githubusercontent.com/68994507/181349358-66b73f16-3f6e-455e-b111-eabd7c8ffabc.png)

Desktop
![View exercise list (desktop) #1](https://user-images.githubusercontent.com/68994507/181350244-23f9f625-e44b-486e-bc72-47720fcdfef4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include a few exercises as dummy data in the exercises table

### ☁️ Server Tasks

- [x] Handle get requests for retrieving all exercises in database
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create page for viewing exercises
- [x] Create a component to render exercise cards from the exercises database table

### 🧑‍⚕️ Clean Up Tasks

- [x] Check for card's responsiveness
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
