### ISSUE TITLE
User can add exercises from list

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their own profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their own profile including their usernames

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Add from Exercise List (mobile) #1](https://user-images.githubusercontent.com/68994507/181937560-52e11c76-26a9-40af-9a26-83c2dba8f7af.png)

Desktop
![Group 1](https://user-images.githubusercontent.com/68994507/181358045-f6125a23-51db-4679-89a3-14c2e216b1e0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include a workout placeholder for adding exercises

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive post requests for saving exercise sets; sets must include existing workout id and exercise id
- [x] Update `server/index.js` to receive get requests for displaying all exercises in an existing workout, must include workout id
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to identify (change color of) selected exercises from the list
- [x] Update component so that if user clicks twice on an exercise, the exercise is unselected
- [x] Add component which allows users to clear all selected exercises
- [x] Add component which saves exercises to workout
- [x] On desktop, create component which displays selected exercises listed in the bottom corner
- [x] Make selector collapsable
- [x] Add fetch post request to 'add all' button click which adds exercises (sets table) to database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
