### ISSUE TITLE
User view a workout's exercises and sets

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a workout's exercises and sets

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After adding exercises to a workout, the workout's exercises and sets are displayed in a new page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![View workout's exercises](https://user-images.githubusercontent.com/68994507/182444015-ebd7c744-1cb7-41c0-b8c1-37c9eb5c161c.png)

Desktop
![Create Custom Exercises (desktop) #3](https://user-images.githubusercontent.com/68994507/182443981-cc39e78c-051d-4320-a3ab-ab061dbb4a24.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create workout component for holding all exercises
- [x] Add exercise cards to component for displaying each exercise
- [x] Add set rows inside each exercise card for displaying each set
- [x] Add fetch request to retrieve a workout's exercises based on the workout id
- [x] Make sure the exercise cards are responsive

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
