### ISSUE TITLE
User can edit and add sets

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add sets to an exercise and edit the values of reps, weights and done

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the workout page, under each exercise set, a user is able to edit how many reps and the weight used in the set. The user can then mark the set completed (done arrow).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 12](https://user-images.githubusercontent.com/68994507/182723678-57612982-3cd6-4bc2-91e3-42d17128f824.png)

Desktop
![Group 12 (1)](https://user-images.githubusercontent.com/68994507/182723675-79af6dc0-bba5-4931-a6a4-1f379b5a9381.png)
![Edit sets (desktop) #3](https://user-images.githubusercontent.com/68994507/182723688-c3dd2bff-87cc-4dc9-bee0-63f36ebe3c46.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include a few exercises in a workout

### ☁️ Server Tasks

- [x] Update `server/index.js` to join sets and exercise table to include an exercise's name, equipment, sets
- [x] Update `server/index.js` to receive patch requests to update sets table (reps and weight)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create new component for exercises (split from workout)
- [x] Add an exercise array state to workout component containing each exercise
- [x] Map each exercise retrieved from the fetch request into separate components
- [x] Create new component for set inputs (split from exercise)
- [x] Add a set array state to exercise component containing each set
- [x] Map each set from exercise, defaults to 1 set
- [x] Add functionality to 'add set' button adding new set to state and re-rendering set rows
- [x] Add toggle for completing a set 'done button'
- [x] Add state change inside workout component for updating specific exercise set values
- [x] Add on change event listener to set inputs, updating workout component's state
- [x] Check if changes are being updated to state

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
