### ISSUE TITLE
User can delete exercise from workout

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an exercise from a workout

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking on an icon next to an exercise's name, a user can toggle a tooltip to delete an exercise from the workout.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 11](https://user-images.githubusercontent.com/68994507/182725804-ec400aed-da13-421c-9e88-0754e05e131a.png)

Desktop
![Group 13](https://user-images.githubusercontent.com/68994507/182725814-da06aef8-9458-4570-8f6d-488dd303d481.png)
![Delete Exercise (desktop) #1](https://user-images.githubusercontent.com/68994507/182725824-cdc0c7d4-f531-45d6-a25f-401d1178d960.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive delete requests of an exercises in the sets table
- [x] Check that the request contains a workout id and exercise id
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add button to the exercise component for options, next to exercise name
- [x] Create a button that appears when clicking on the 'options' once, showing a delete exercise option
- [x] Add function for handling on click on the delete option which removes the selected exercise and its sets from the page
- [x] Make sure the deleted exercise is removed from the workout's state
- [x] Make sure deleting an exercise removes it from the database 'sets' table

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
