### ISSUE TITLE
User can save workouts

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can save completed workouts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After completing a workout, user can click on a icon (mobile) or save button (desktop) and all exercises that are 'done' are saved.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 12](https://user-images.githubusercontent.com/68994507/182921082-6e2ff43e-bdad-4cc7-8f63-f5b10939b42d.png)

Desktop
![Group 14](https://user-images.githubusercontent.com/68994507/182921076-cd023f95-2636-4f8a-9763-3b0dd71182f8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive post request for multiple sets
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a save workout button
- [x] Create a modal for confirmation with two buttons, save and cancel
- [x] Add on-click event to save workout button to trigger modal
- [x] Add functionality to cancel button which closes the modal
- [x] Create post request to server after confirming for updating all sets
- [x] Link delete exercise function to saving exercise in order to delete exercises that were initially added but do not have completed sets
- [x] Sort the set order of all done sets before adding to database
- [x] Make sure all sets are updated/added to database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
