### ISSUE TITLE
User can view workouts history

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view previously completed workouts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can click on the profile icon (mobile) or profile on navbar (desktop) to open their profile which displays previously saved (completed) workouts

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 14](https://user-images.githubusercontent.com/68994507/182979343-ec22c41e-bed8-4f7f-90b7-f75fb24dfb7b.png)

Desktop
![View workout history (mobile) #1](https://user-images.githubusercontent.com/68994507/182979348-02448fe4-b7f3-46fa-b37e-17e19815bc8a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include dummy data for testing if only a user's completed workouts are returned from get request

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle get requests for all workouts a user has completed/saved
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create page component for user profile
- [x] Create a component to display the total number of workouts done
- [x] Create a component to display workouts as cards showing two columns: exercise and heaviest/best set
- [x] Create fetch request to database to retrieve workouts based on user id
- [x] Manipulate response object grouping by workout and exercises
- [x] Map each workout to create a card for each
- [x] Make sure all user workouts are displayed
- [x] Create hash routes to navigate between creating workout, exercises and profile
- [x] Link anchors and icons to each route
- [x] Test navigation between each page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
